### ISSUE TITLE
[Prettier] Proposal for change 

### ISSUE THREAD

**Issue by joseacabaneros** [empathyco/eslint-config#3]
@davidglezz suggests the next changes in Prettier:
- `trailingComma: 'all'` https://github.com/empathyco/eslint-config/pull/1#discussion_r1805418491
- `vueIndentScriptAndStyle: false` https://github.com/empathyco/eslint-config/pull/1#discussion_r1805422171

**Comment by davidglezz** [comment]
## Common scenario:

With `trailingComma: 'none',` :
```diff
const x = {
-  a: 3
+  a: 3,
+  b: 4
}
```

vs `trailingComma: 'all',` (the default)

```diff
const x = {
   a: 3,
+  b: 4,
}
```
